### ISSUE TITLE
Endpoint reached. Nothing happens

### ISSUE THREAD

**Issue by brenjt** [andacata/HybridIgniter#2]
I followed the instructions on the use. When I try to login via any provider at: www.mydomainname.com/hauth/login/twitter it loads a page saying:

```
HybridAuth
Open Source Social Sign On PHP Library. 
hybridauth.sourceforge.net/
```

It never works. I have valid api credentials for twitter and facebook but both load this page and nothing else happens. Any tips would be greatly appreciated.

My log says:

```
Hybrid_Provider_Adapter::login( facebook ), redirect the user to login_start URL. -- Array
(
    [hauth_return_to] => http://www.sitename.com/hauth/login/facebook
    [hauth_token] => 6vjglu8usmsjqsi74cku8o85j3
    [hauth_time] => 1335997302
    [login_start] => http://sitename.com/hauth/endpoint?hauth.start=facebook&hauth.time=1335997302
    [login_done] => http://sitename.com/hauth/endpoint?hauth.done=facebook
)

INFO -- 127.0.0.1 -- 2012-05-03T00:21:42+02:00 -- Enter Hybrid_Auth::redirect( http://sitename.com/hauth/endpoint?hauth.start=facebook&hauth.time=1335997302, PHP )
```

**Comment by sbangani** [comment]
HybridIgniter seems to have problems and outdated, I am trying to setUserStatus but it not allowing me       
 I am using codeigniter framework
